# Generated by Django 4.0.5 on 2022-07-07 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('research', '0002_initialize_fields'),
        ('participant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormMetadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('research', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='research.research')),
            ],
        ),
        migrations.CreateModel(
            name='FormParticipantMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status',
                 models.CharField(blank=True, choices=[('N', 'New'), ('R', 'Under Review'), ('D', 'Done')], default='N',
                                  max_length=1)),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('form',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.formmetadata')),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='participant.participant')),
            ],
        ),
    ]
