# Generated by Django 4.0.5 on 2022-07-08 14:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ('participant', '0001_initial'),
        ('research', '0002_initialize_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchAttending',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('participant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                                  to='participant.participant')),
                ('research',
                 models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='research.research')),
            ],
        ),
    ]
