# Generated by Django 4.0.6 on 2022-08-05 07:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('research', '0003_researchattending'),
    ]

    operations = [
        migrations.AddField(
            model_name='researchattending',
            name='status',
            field=models.CharField(
                choices=[('AS', 'Assigned'), ('IP', 'InProgress'), ('DR', 'InProgress'), ('DO', 'Done')], default='AS',
                max_length=2),
        ),
    ]
