# Generated by Django 4.0.5 on 2022-07-11 18:53

from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ('researcher', '0001_initial'),
    ]

    def generate_data(apps, schema_editor):
        from researcher.models import Researcher
        test_data = [('researcher_1@gmail.com', 'researcher_1', 'researcher_1', 'researcher', '1', 1111111111),
                     ('researcher_2@gmail.com', 'researcher_2', 'researcher_2', 'researcher', '2', 2222222222),
                     ('researcher_3@gmail.com', 'researcher_3', 'researcher_3', 'researcher', '3', 3333333333),
                     ('researcher_4@gmail.com', 'researcher_4', 'researcher_4', 'researcher', '4', 4444444444),
                     ('researcher_5@gmail.com', 'researcher_5', 'researcher_5', 'researcher', '5', 5555555555),
                     ('researcher_6@gmail.com', 'researcher_6', 'researcher_6', 'researcher', '6', 6666666666),
                     ('researcher_7@gmail.com', 'researcher_7', 'researcher_7', 'researcher', '7', 7777777777),
                     ('researcher_8@gmail.com', 'researcher_8', 'researcher_8', 'researcher', '8', 8888888888),
                     ('researcher_9@gmail.com', 'researcher_9', 'researcher_9', 'researcher', '9', 9999999999)]

        with transaction.atomic():
            for email, username, password, first_name, last_name, phone_number in test_data:
                researcher = Researcher.create(email=email, username=username, password=password, first_name=first_name,
                                               last_name=last_name, phone_number=phone_number)
                researcher.save()

    operations = [
        migrations.RunPython(generate_data),
    ]
