# Generated by Django 4.0.6 on 2022-07-21 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('base_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_user',
                 models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='base_user.baseuser')),
            ],
        ),
    ]
