# Generated by Django 4.0.5 on 2022-07-11 18:53

from django.db import migrations, transaction


class Migration(migrations.Migration):
    dependencies = [
        ('participant', '0001_initial'),
    ]

    def generate_data(apps, schema_editor):
        from participant.models import Participant
        test_data = [('participant_1@gmail.com', 'participant_1', 'participant_1', 'participant', '1', 1111111111),
                     ('participant_2@gmail.com', 'participant_2', 'participant_2', 'participant', '2', 2222222222),
                     ('participant_3@gmail.com', 'participant_3', 'participant_3', 'participant', '3', 3333333333),
                     ('participant_4@gmail.com', 'participant_4', 'participant_4', 'participant', '4', 4444444444),
                     ('participant_5@gmail.com', 'participant_5', 'participant_5', 'participant', '5', 5555555555),
                     ('participant_6@gmail.com', 'participant_6', 'participant_6', 'participant', '6', 6666666666),
                     ('participant_7@gmail.com', 'participant_7', 'participant_7', 'participant', '7', 7777777777),
                     ('participant_8@gmail.com', 'participant_8', 'participant_8', 'participant', '8', 8888888888),
                     ('participant_9@gmail.com', 'participant_9', 'participant_9', 'participant', '9', 9999999999)]

        with transaction.atomic():
            for email, username, password, first_name, last_name, phone_number in test_data:
                participant = Participant.create(email=email, username=username, password=password,
                                                 first_name=first_name, last_name=last_name, phone_number=phone_number)
                participant.save()

    operations = [
        migrations.RunPython(generate_data),
    ]
